name: Mirror and prepend fragment

on:
  # هر 3 ساعت یکبار (UTC)
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch: {}
  push:
    paths:
      - ".github/workflows/mirror.yml"
      - "prefix.txt"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch source
        env:
          SOURCE_URL: https://raw.githubusercontent.com/hiddify/hiddify-app/refs/heads/main/test.configs/fragment
        run: |
          set -euo pipefail
          curl -fsSL "$SOURCE_URL" -o source.txt

      # یکی از دو بخش زیر را انتخاب کنید:

      # گزینه A) استفاده از prefix.txt ثابت
      - name: Build combined file (with prefix.txt)
        run: |
          mkdir -p output
          cat prefix.txt source.txt > output/fragment
            - name: Commit and push if changed
        env:
          BRANCH: main   # اگر شاخه‌ی پیش‌فرض شما چیز دیگری است، همین را عوض کنید
        run: |
          set -e
          if ! git diff --quiet -- output/fragment; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add output/fragment
            git commit -m "Update fragment from upstream [skip ci]"
            # در حالت detached HEAD مستقیماً به شاخه‌ی مقصد push می‌کنیم
            git push origin HEAD:$BRANCH
          else
            echo "No changes to commit."
          fi

